[tool.pylint.messages_control]
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "invalid-name",
    "too-few-public-methods",
    "redefined-outer-name",
    "fixme"
]

[tool.flake8]
    exclude = ".venv"
    max-complexity = 10
    max-line-length = 88
    extend-ignore = """
        W503,
        E203,
        E701,
    """
    per-file-ignores = """
        __init__.py: F401
    """

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"
multi_line_output = 3
length_sort = true
